/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV.GUI;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author chihi
 */
public class Main extends javax.swing.JFrame {

    private JPanel childPanel;
    public Image icon = Toolkit.getDefaultToolkit().getImage("image/sachBook512px.png");
    /**
     * Creates new form Main
     */
    public Main() {
        this.setIconImage(icon);
        initComponents();
//        this.set
        //
        showPanel(new pnQuanLySachGUI());
        btnQuanLySach.setBackground(new Color(242,153,74));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnLeft = new javax.swing.JPanel();
        btnQuanLySach = new javax.swing.JButton();
        btnDocGia = new javax.swing.JButton();
        btnPhieuMTP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThongKe = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 153, 74));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Mượn Trả Sách Thư Viện");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerSize(10);

        pnLeft.setBackground(new java.awt.Color(63, 74, 89));
        pnLeft.setMinimumSize(new java.awt.Dimension(309, 790));
        pnLeft.setPreferredSize(new java.awt.Dimension(309, 790));
        pnLeft.setVerifyInputWhenFocusTarget(false);

        btnQuanLySach.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanLySach.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnQuanLySach.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien_1_1_1\\image\\qlBook.png")); // NOI18N
        btnQuanLySach.setText("  Quản lý sách");
        btnQuanLySach.setHideActionText(true);
        btnQuanLySach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLySachActionPerformed(evt);
            }
        });

        btnDocGia.setBackground(new java.awt.Color(255, 255, 255));
        btnDocGia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDocGia.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien_1_1_1\\image\\qlDocGia64px_ok.png")); // NOI18N
        btnDocGia.setText("Quản lý độc giả");
        btnDocGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocGiaActionPerformed(evt);
            }
        });

        btnPhieuMTP.setBackground(new java.awt.Color(255, 255, 255));
        btnPhieuMTP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPhieuMTP.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien_Update2_0\\image\\qlPhieu.png")); // NOI18N
        btnPhieuMTP.setText(" Quản lý phiếu");
        btnPhieuMTP.setToolTipText("");
        btnPhieuMTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuMTPActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien_1_1_1\\image\\logoBook.png")); // NOI18N

        btnThongKe.setBackground(new java.awt.Color(255, 255, 255));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien_Update2_0\\image\\thongke.png")); // NOI18N
        btnThongKe.setText(" Thống kê");
        btnThongKe.setToolTipText("");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPhieuMTP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(btnDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addComponent(btnQuanLySach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPhieuMTP, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jSplitPane1.setLeftComponent(pnLeft);

        pnRight.setMinimumSize(new java.awt.Dimension(1750, 790));
        pnRight.setPreferredSize(new java.awt.Dimension(1750, 790));
        pnRight.setLayout(new java.awt.BorderLayout());
        jSplitPane1.setRightComponent(pnRight);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLySachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLySachActionPerformed
        // TODO add your handling code here:
        showPanel(new pnQuanLySachGUI());
        //
        btnQuanLySach.setBackground(new Color(242,153,74));
        btnThongKe.setBackground(new Color(255,255,255));
        btnDocGia.setBackground(new Color(255,255,255));
        btnPhieuMTP.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnQuanLySachActionPerformed

    private void btnDocGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocGiaActionPerformed
        // TODO add your handling code here:
        showPanel(new pnQuanLyDocGiaGUI());
        //
        btnQuanLySach.setBackground(new Color(255,255,255));
        btnThongKe.setBackground(new Color(255,255,255));
        btnDocGia.setBackground(new Color(242,153,74));
        btnPhieuMTP.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnDocGiaActionPerformed

    private void btnPhieuMTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuMTPActionPerformed
        // TODO add your handling code here:
        showPanel(new pnQuanLyPhieuGUI());
        //
        btnQuanLySach.setBackground(new Color(255,255,255));
        btnThongKe.setBackground(new Color(255,255,255));
        btnDocGia.setBackground(new Color(255,255,255));
        btnPhieuMTP.setBackground(new Color(242,153,74));
    }//GEN-LAST:event_btnPhieuMTPActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        showPanel(new pnThongKeGUI());
        //
        btnPhieuMTP.setBackground(new Color(255,255,255));
        btnQuanLySach.setBackground(new Color(255,255,255));
        btnDocGia.setBackground(new Color(255,255,255));
        btnThongKe.setBackground(new Color(242,153,74));
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocGia;
    private javax.swing.JButton btnPhieuMTP;
    private javax.swing.JButton btnQuanLySach;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnRight;
    // End of variables declaration//GEN-END:variables
    private void showPanel(JPanel panel){
        childPanel = panel;
        pnRight.removeAll();
        pnRight.add(childPanel);
        pnRight.validate(); 
    }
}
