/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV.GUI;

import MyCustom.MyDialog;
import MyCustom.XuLyFileExcel;
import QLTV.BUS.SachBUS;
import QLTV.BUS.TacGiaBUS;
import QLTV.BUS.TheLoaiBUS;
import QLTV.BUS.TheLoaiSachBUS;
import QLTV.DAO.MyConnect;
import QLTV.DTO.Sach;
import QLTV.DTO.TacGia;
import QLTV.DTO.TheLoai;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author chihi
 */
public class pnQuanLySachGUI extends javax.swing.JPanel {

    DefaultTableModel tabModelTacGia,tabModelTheLoai, tabModelSach;
    public ArrayList<Sach> sachList ;    
    public SachBUS sachBUS; 
    public TheLoaiBUS theLoaiBUS; 
    public TacGiaBUS tacGiaBUS; 
    public TheLoaiSachBUS theLoaiSachBUS;
    /**
     * Creates new form pnQuanLySachGUI
     */
    public pnQuanLySachGUI() {
        new MyConnect();
        initComponents();
//        this.setLocationRelativeTo(null);
        sachBUS = new SachBUS();
        theLoaiBUS = new TheLoaiBUS();
        tacGiaBUS = new TacGiaBUS();
        theLoaiSachBUS = new TheLoaiSachBUS();
        
        tabModelTacGia = (DefaultTableModel) jtblListTacGia.getModel();
        tabModelTheLoai = (DefaultTableModel) jtblListTheLoai.getModel();
        tabModelSach = (DefaultTableModel) jtblListSach.getModel();
        showStartSach();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        dialogChinhSuaSach = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jlblTitle = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtfMaSachDialog = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtfTenSachDialog = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtfNhaXuatBanDialog = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jtfGiaTienDialog = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jcbbTenTGDialog = new javax.swing.JComboBox<>();
        jcbbTheLoaiDialog = new javax.swing.JComboBox<>();
        jbtnLuuEdit = new javax.swing.JButton();
        jbtnThoatEdit = new javax.swing.JButton();
        jbtnResetEditS = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jtfSoLuongDialog = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlSach_TimTaiLieu = new javax.swing.JPanel();
        jplTimKiemSach = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlblTongSoSachSachTK = new javax.swing.JLabel();
        jcbbListMaxMinSachTk = new javax.swing.JComboBox<>();
        jbtnXemAllSachTK = new javax.swing.JButton();
        jtfMaTaiLieuSachTK = new javax.swing.JTextField();
        jcbbNXBSachTK = new javax.swing.JComboBox<>();
        jcbbTacGiaSachTK = new javax.swing.JComboBox<>();
        jlblTheLoaiSachTK = new javax.swing.JLabel();
        jlblMaTaiLieuSachTK = new javax.swing.JLabel();
        jbtnTimKiemSachTK = new javax.swing.JButton();
        jlblTacGiaSachTK = new javax.swing.JLabel();
        jrdbCoBanSachTK = new javax.swing.JRadioButton();
        jrdbNangCaoSachTK = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListSach = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jbtnChinhSuaSachTK = new javax.swing.JButton();
        btnXoaSachTK = new javax.swing.JButton();
        btnXuatFileSach = new javax.swing.JButton();
        jtpSach_ThemTT = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jbtnThemTheLoaiTTT = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jtfMaTheLoaiTTT = new javax.swing.JTextField();
        jtfTenTheLoaiTTT = new javax.swing.JTextField();
        jbtnXoaTheLoaiTTT = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblListTheLoai = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        jbtnSuaTheLoaiTTT = new javax.swing.JButton();
        jbtnXoaTrangTheLoaiTTT = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jbtnSuaTacGiaTTT = new javax.swing.JButton();
        jtfTenTacGiaTTT = new javax.swing.JTextField();
        jtfMaTacGiaTTT = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jbtnThemTacGiaTTT = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblListTacGia = new javax.swing.JTable();
        jbtnXoaTacGiaTTT = new javax.swing.JButton();
        jbtnXoaTrangTacGiaTTT2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfMaSachTTT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfTenSachTTT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfNXBTTT = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfSoLuongTTT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfGiaTienTTT = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcbbTenTGTTS = new javax.swing.JComboBox<>();
        jcbbTenTLTTS = new javax.swing.JComboBox<>();
        jbtnThemSachTTT = new javax.swing.JButton();
        jlblTongSoSachTTT = new javax.swing.JLabel();
        jbtnXoaTrangSachTTT = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlblTitle.setText("Chỉnh sửa thông tin sách");
        jPanel4.add(jlblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Mã sách :");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 110, -1));

        jtfMaSachDialog.setEditable(false);
        jtfMaSachDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jtfMaSachDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 240, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("Tên tác giả :");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("Tên sách :");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, -1));

        jtfTenSachDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jtfTenSachDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 240, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("Nhà xuất bản :");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, -1));

        jtfNhaXuatBanDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jtfNhaXuatBanDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 240, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("Giá tiền :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, -1));

        jtfGiaTienDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jtfGiaTienDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 240, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Thể loại :");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 110, -1));

        jcbbTenTGDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jcbbTenTGDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 240, -1));

        jcbbTheLoaiDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jcbbTheLoaiDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 240, -1));

        jbtnLuuEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnLuuEdit.setText("Lưu");
        jbtnLuuEdit.setPreferredSize(new java.awt.Dimension(113, 31));
        jbtnLuuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLuuEditActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLuuEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 130, 40));

        jbtnThoatEdit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnThoatEdit.setText("Thoát");
        jbtnThoatEdit.setPreferredSize(new java.awt.Dimension(113, 31));
        jbtnThoatEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoatEditActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnThoatEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 130, 40));

        jbtnResetEditS.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\Refresh-icon.png")); // NOI18N
        jbtnResetEditS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetEditSActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnResetEditS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("Số lượng :");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 120, -1));

        jtfSoLuongDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel4.add(jtfSoLuongDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 240, -1));

        javax.swing.GroupLayout dialogChinhSuaSachLayout = new javax.swing.GroupLayout(dialogChinhSuaSach.getContentPane());
        dialogChinhSuaSach.getContentPane().setLayout(dialogChinhSuaSachLayout);
        dialogChinhSuaSachLayout.setHorizontalGroup(
            dialogChinhSuaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        dialogChinhSuaSachLayout.setVerticalGroup(
            dialogChinhSuaSachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jplTimKiemSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jplTimKiemSach.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setMaximumSize(new java.awt.Dimension(1606, 219));
        jPanel3.setMinimumSize(new java.awt.Dimension(1606, 219));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblTongSoSachSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTongSoSachSachTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTongSoSachSachTK.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jlblTongSoSachSachTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jlblTongSoSachSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, 270, 33));

        jcbbListMaxMinSachTk.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jcbbListMaxMinSachTk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbListMaxMinSachTkActionPerformed(evt);
            }
        });
        jPanel3.add(jcbbListMaxMinSachTk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 70, 270, -1));

        jbtnXemAllSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnXemAllSachTK.setText("Xem tất cả");
        jbtnXemAllSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXemAllSachTKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnXemAllSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jtfMaTaiLieuSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfMaTaiLieuSachTK.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtfMaTaiLieuSachTK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jtfMaTaiLieuSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 269, -1));

        jcbbNXBSachTK.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jcbbNXBSachTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcbbNXBSachTK.setBorder(null);
        jcbbNXBSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbNXBSachTKActionPerformed(evt);
            }
        });
        jPanel3.add(jcbbNXBSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 269, 40));

        jcbbTacGiaSachTK.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jcbbTacGiaSachTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcbbTacGiaSachTK.setBorder(null);
        jcbbTacGiaSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbTacGiaSachTKActionPerformed(evt);
            }
        });
        jPanel3.add(jcbbTacGiaSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 269, 40));

        jlblTheLoaiSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTheLoaiSachTK.setText("Nhà xuất bản :");
        jPanel3.add(jlblTheLoaiSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jlblMaTaiLieuSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblMaTaiLieuSachTK.setText("Mã tài liệu :");
        jPanel3.add(jlblMaTaiLieuSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jbtnTimKiemSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnTimKiemSachTK.setText("Tìm kiếm");
        jbtnTimKiemSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTimKiemSachTKActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnTimKiemSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 155, -1));

        jlblTacGiaSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTacGiaSachTK.setText("Tác giả :");
        jPanel3.add(jlblTacGiaSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        buttonGroup1.add(jrdbCoBanSachTK);
        jrdbCoBanSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jrdbCoBanSachTK.setText("Cơ bản");
        jrdbCoBanSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdbCoBanSachTKActionPerformed(evt);
            }
        });
        jPanel3.add(jrdbCoBanSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        buttonGroup1.add(jrdbNangCaoSachTK);
        jrdbNangCaoSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jrdbNangCaoSachTK.setText("Nâng cao");
        jrdbNangCaoSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdbNangCaoSachTKActionPerformed(evt);
            }
        });
        jPanel3.add(jrdbNangCaoSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Tìm kiếm theo :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Xem theo :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 70, 150, -1));

        jplTimKiemSach.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setPreferredSize(new java.awt.Dimension(1750, 400));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jtblListSach.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jtblListSach.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtblListSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblListSach.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtblListSach.setRowHeight(35);
        jScrollPane1.setViewportView(jtblListSach);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnChinhSuaSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnChinhSuaSachTK.setText("Sửa");
        jbtnChinhSuaSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChinhSuaSachTKActionPerformed(evt);
            }
        });
        jPanel12.add(jbtnChinhSuaSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 168, 50));

        btnXoaSachTK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnXoaSachTK.setText("Xóa");
        btnXoaSachTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSachTKActionPerformed(evt);
            }
        });
        jPanel12.add(btnXoaSachTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, 160, 50));

        btnXuatFileSach.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnXuatFileSach.setText("Xuất file");
        btnXuatFileSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileSachActionPerformed(evt);
            }
        });
        jPanel12.add(btnXuatFileSach, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 160, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jplTimKiemSach.add(jPanel10, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnlSach_TimTaiLieuLayout = new javax.swing.GroupLayout(pnlSach_TimTaiLieu);
        pnlSach_TimTaiLieu.setLayout(pnlSach_TimTaiLieuLayout);
        pnlSach_TimTaiLieuLayout.setHorizontalGroup(
            pnlSach_TimTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 1752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlSach_TimTaiLieuLayout.setVerticalGroup(
            pnlSach_TimTaiLieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplTimKiemSach, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tìm kiếm tài liệu", pnlSach_TimTaiLieu);

        jtpSach_ThemTT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel17.setText("Thêm thể loại");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 28, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Mã thể loại :");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 117, -1, -1));

        jbtnThemTheLoaiTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnThemTheLoaiTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\add-icon.png")); // NOI18N
        jbtnThemTheLoaiTTT.setText("Thêm");
        jbtnThemTheLoaiTTT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnThemTheLoaiTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemTheLoaiTTTActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnThemTheLoaiTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 252, -1, 43));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel20.setText("Tên thể loại : ");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 195, -1, -1));

        jtfMaTheLoaiTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfMaTheLoaiTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(jtfMaTheLoaiTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 114, 231, -1));

        jtfTenTheLoaiTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfTenTheLoaiTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel5.add(jtfTenTheLoaiTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 192, 231, -1));

        jbtnXoaTheLoaiTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnXoaTheLoaiTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\delete-icon.png")); // NOI18N
        jbtnXoaTheLoaiTTT.setText("Xóa");
        jbtnXoaTheLoaiTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaTheLoaiTTTActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnXoaTheLoaiTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 252, -1, 43));

        jtblListTheLoai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtblListTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thể loại", "Tên thể loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblListTheLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtblListTheLoai.setRowHeight(35);
        jtblListTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblListTheLoaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtblListTheLoai);
        if (jtblListTheLoai.getColumnModel().getColumnCount() > 0) {
            jtblListTheLoai.getColumnModel().getColumn(0).setPreferredWidth(150);
            jtblListTheLoai.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 15, 450, 280));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 15, 11, 280));

        jbtnSuaTheLoaiTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnSuaTheLoaiTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\Pencil-icon.png")); // NOI18N
        jbtnSuaTheLoaiTTT.setText("Sửa");
        jbtnSuaTheLoaiTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaTheLoaiTTTActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnSuaTheLoaiTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 252, 117, 43));

        jbtnXoaTrangTheLoaiTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\Refresh-icon.png")); // NOI18N
        jbtnXoaTrangTheLoaiTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaTrangTheLoaiTTTActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnXoaTrangTheLoaiTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 52, -1));

        jtpSach_ThemTT.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 950, 310));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setText("Thêm tác giả");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 28, -1, -1));

        jbtnSuaTacGiaTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnSuaTacGiaTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\Pencil-icon.png")); // NOI18N
        jbtnSuaTacGiaTTT.setText("Sửa");
        jbtnSuaTacGiaTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSuaTacGiaTTTActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnSuaTacGiaTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 43));

        jtfTenTacGiaTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfTenTacGiaTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel6.add(jtfTenTacGiaTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 176, 231, -1));

        jtfMaTacGiaTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfMaTacGiaTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel6.add(jtfMaTacGiaTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 104, 231, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel21.setText("Mã tác giả :");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setText("Tên tác giả : ");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 182, -1, -1));

        jbtnThemTacGiaTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnThemTacGiaTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\add-icon.png")); // NOI18N
        jbtnThemTacGiaTTT.setText("Thêm");
        jbtnThemTacGiaTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemTacGiaTTTActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnThemTacGiaTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 269, -1, 43));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 15, 10, 305));

        jtblListTacGia.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtblListTacGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tác giả", "Tên tác giả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblListTacGia.setRowHeight(35);
        jtblListTacGia.setRowMargin(5);
        jtblListTacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblListTacGiaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtblListTacGia);
        if (jtblListTacGia.getColumnModel().getColumnCount() > 0) {
            jtblListTacGia.getColumnModel().getColumn(0).setPreferredWidth(150);
            jtblListTacGia.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        jPanel6.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 15, 450, 305));

        jbtnXoaTacGiaTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnXoaTacGiaTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\delete-icon.png")); // NOI18N
        jbtnXoaTacGiaTTT.setText("Xóa");
        jbtnXoaTacGiaTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaTacGiaTTTActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnXoaTacGiaTTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 269, -1, 43));

        jbtnXoaTrangTacGiaTTT2.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\Refresh-icon.png")); // NOI18N
        jbtnXoaTrangTacGiaTTT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaTrangTacGiaTTT2ActionPerformed(evt);
            }
        });
        jPanel6.add(jbtnXoaTrangTacGiaTTT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 25, 52, -1));

        jtpSach_ThemTT.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 960, 350));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setText("Thêm thông tin sách");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Mã sách :");

        jtfMaSachTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfMaSachTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Tên tác giả :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Tên sách :");

        jtfTenSachTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfTenSachTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Nhà xuất bản :");

        jtfNXBTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfNXBTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Số lượng :");

        jtfSoLuongTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfSoLuongTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setText("Giá tiền :");

        jtfGiaTienTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtfGiaTienTTT.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Thể loại :");

        jcbbTenTGTTS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jcbbTenTGTTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbTenTGTTSActionPerformed(evt);
            }
        });

        jcbbTenTLTTS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jcbbTenTLTTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbbTenTLTTSActionPerformed(evt);
            }
        });

        jbtnThemSachTTT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnThemSachTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\add-icon.png")); // NOI18N
        jbtnThemSachTTT.setText("Thêm mới");
        jbtnThemSachTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThemSachTTTActionPerformed(evt);
            }
        });

        jlblTongSoSachTTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblTongSoSachTTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTongSoSachTTT.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbtnXoaTrangSachTTT.setIcon(new javax.swing.ImageIcon("C:\\Users\\chihi\\OneDrive\\Documents\\NetBeansProjects\\QuanLyThuVien\\image\\Refresh-icon.png")); // NOI18N
        jbtnXoaTrangSachTTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnXoaTrangSachTTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnXoaTrangSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblTongSoSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jtfSoLuongTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jtfNXBTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfTenSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbbTenTLTTS, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfGiaTienTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfMaSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jbtnThemSachTTT)
                                .addGap(89, 89, 89)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbbTenTGTTS, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnXoaTrangSachTTT)
                            .addComponent(jlblTongSoSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel9)))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfMaSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcbbTenTGTTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTenSachTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jtfNXBTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSoLuongTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfGiaTienTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jcbbTenTLTTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jbtnThemSachTTT)
                .addGap(29, 29, 29))
        );

        jtpSach_ThemTT.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, 520, 670));

        jTabbedPane1.addTab("Thêm thông tin sách", jtpSach_ThemTT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1748, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrdbCoBanSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbCoBanSachTKActionPerformed
        // TODO add your handling code here:
        jlblTacGiaSachTK.setVisible(false);
        jlblTheLoaiSachTK.setVisible(false);
        jlblMaTaiLieuSachTK.setVisible(true);
        jcbbTacGiaSachTK.setVisible(false);
        jcbbNXBSachTK.setVisible(false);
        jtfMaTaiLieuSachTK.setVisible(true);
        jbtnTimKiemSachTK.setVisible(true);
    }//GEN-LAST:event_jrdbCoBanSachTKActionPerformed

    private void jrdbNangCaoSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdbNangCaoSachTKActionPerformed
        // TODO add your handling code here:
        jlblTacGiaSachTK.setVisible(true);
        jlblTheLoaiSachTK.setVisible(true);
        jlblMaTaiLieuSachTK.setVisible(false);
        jcbbTacGiaSachTK.setVisible(true);
        jcbbNXBSachTK.setVisible(true);
        jtfMaTaiLieuSachTK.setVisible(false);
        jbtnTimKiemSachTK.setVisible(false);
    }//GEN-LAST:event_jrdbNangCaoSachTKActionPerformed

    private void jbtnTimKiemSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTimKiemSachTKActionPerformed
        // TODO add your handling code here:
        if(jtfMaTaiLieuSachTK.getText()==""){
            new MyDialog(" Vui lòng nhập thông tin cần tìm kiếm",MyDialog.ERROR_DIALOG);
        }else{
            ArrayList<Sach> a = sachBUS.docDuLieuTimKiemSach(jtfMaTaiLieuSachTK.getText(),null, false, false);
            loadTableTimKiem(a);
            jtfMaTaiLieuSachTK.setText("");
            jtfMaTaiLieuSachTK.requestFocus();
        }
    }//GEN-LAST:event_jbtnTimKiemSachTKActionPerformed

    private void jbtnXemAllSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXemAllSachTKActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> a = sachBUS.getDuLieuSach();
        loadTableTimKiem(a);
    }//GEN-LAST:event_jbtnXemAllSachTKActionPerformed

    private void jcbbListMaxMinSachTkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbListMaxMinSachTkActionPerformed
        // TODO add your handling code here:
        String a = (String) jcbbListMaxMinSachTk.getSelectedItem();
        ArrayList<Sach> b = sachBUS.getListMinMaxSoGia(a);
        loadTableTimKiem(b);
        
    }//GEN-LAST:event_jcbbListMaxMinSachTkActionPerformed

    private void jbtnChinhSuaSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChinhSuaSachTKActionPerformed
        // TODO add your handling code here:
        int row = jtblListSach.getSelectedRow();
        if(sachList.size() == 0){
            new MyDialog("Hãy nhập dữ liệu cho bảng sách !!!",MyDialog.WARNING_DIALOG);
        }else if(row == -1 ){
            new MyDialog("Hãy chọn sách muốn sửa thông tin !!!", MyDialog.WARNING_DIALOG);
        }else{
            String maSach = jtblListSach.getValueAt(row,1).toString();
            jtfMaSachDialog.setText(maSach);
            String[] tenTacGia = jtblListSach.getValueAt(row,2).toString().split("_");
            jcbbTenTGDialog.setSelectedItem(tenTacGia[1]);
            jtfTenSachDialog.setText(jtblListSach.getValueAt(row,3).toString());
            jtfNhaXuatBanDialog.setText(jtblListSach.getValueAt(row,4).toString());
            jtfSoLuongDialog.setText(jtblListSach.getValueAt(row,5).toString());
            jtfGiaTienDialog.setText(jtblListSach.getValueAt(row,6).toString());
            //
            String maTheLoai = theLoaiSachBUS.soSachLayRaMa(maSach, true);
            String tenTheLoai = theLoaiBUS.layMaOrTenTheLoai(maTheLoai,false);
            jcbbTheLoaiDialog.setSelectedItem(tenTheLoai);
            
            jtfMaSachDialog.setEditable(false);
            dialogChinhSuaSach.setSize(540, 650);
            dialogChinhSuaSach.setVisible(true);
            dialogChinhSuaSach.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jbtnChinhSuaSachTKActionPerformed

    private void btnXoaSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSachTKActionPerformed
        // TODO add your handling code here:
        int row = jtblListSach.getSelectedRow();
        String maSach = jtblListSach.getValueAt(row,1).toString();
        boolean a = theLoaiSachBUS.xoaTheLoaiSach(maSach, true);
        boolean b = sachBUS.xoaSach(maSach);
        if(a==true && b==true){
            new MyDialog("Xóa sách mã "+maSach+" thành công !",MyDialog.INFO_DIALOG);
        }else{
            new MyDialog("Xóa sách thất bại !",MyDialog.ERROR_DIALOG);
        }
        loadTableTimKiem(sachBUS.getDuLieuSach());
    }//GEN-LAST:event_btnXoaSachTKActionPerformed

    private void btnXuatFileSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileSachActionPerformed
        // TODO add your handling code here:
        XuLyFileExcel xuatFile = new XuLyFileExcel();
        xuatFile.xuatExcel(jtblListSach);
    }//GEN-LAST:event_btnXuatFileSachActionPerformed

    private void jbtnThemTheLoaiTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemTheLoaiTTTActionPerformed
        // TODO add your handling code here:
        theLoaiBUS.themTheLoai(jtfMaTheLoaiTTT.getText(), jtfTenTheLoaiTTT.getText());
        loadTableTheLoai();
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnThemTheLoaiTTTActionPerformed

    private void jbtnXoaTheLoaiTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaTheLoaiTTTActionPerformed
        // TODO add your handling code here:
        theLoaiSachBUS.xoaTheLoaiSach(jtfMaTheLoaiTTT.getText(), false);
        theLoaiBUS.xoaTheLoai(jtfMaTheLoaiTTT.getText());
        loadTableTheLoai();
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnXoaTheLoaiTTTActionPerformed

    private void jtblListTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListTheLoaiMouseClicked
        // TODO add your handling code here:
        int a = jtblListTheLoai.getSelectedRow();
        jtfMaTheLoaiTTT.setText(jtblListTheLoai.getValueAt(a,0).toString());
        jtfTenTheLoaiTTT.setText(jtblListTheLoai.getValueAt(a,1).toString());
    }//GEN-LAST:event_jtblListTheLoaiMouseClicked

    private void jbtnSuaTheLoaiTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaTheLoaiTTTActionPerformed
        // TODO add your handling code here:
        theLoaiBUS.suaTheLoai(jtfMaTheLoaiTTT.getText(), jtfTenTheLoaiTTT.getText());
        loadTableTheLoai();
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnSuaTheLoaiTTTActionPerformed

    private void jbtnXoaTrangTheLoaiTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaTrangTheLoaiTTTActionPerformed
        // TODO add your handling code here:
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnXoaTrangTheLoaiTTTActionPerformed

    private void jbtnSuaTacGiaTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSuaTacGiaTTTActionPerformed
        // TODO add your handling code here:
        tacGiaBUS.suaTTTacGia(jtfMaTacGiaTTT.getText(), jtfTenTacGiaTTT.getText());
        loadTableTacGia();
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnSuaTacGiaTTTActionPerformed

    private void jbtnThemTacGiaTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemTacGiaTTTActionPerformed
        // TODO add your handling code here:
        tacGiaBUS.themTacGia(jtfMaTacGiaTTT.getText(), jtfTenTacGiaTTT.getText());
        loadTableTacGia();
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnThemTacGiaTTTActionPerformed

    private void jtblListTacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListTacGiaMouseClicked
        // TODO add your handling code here:
        int a = jtblListTacGia.getSelectedRow();
        jtfMaTacGiaTTT.setText(jtblListTacGia.getValueAt(a,0).toString());
        jtfTenTacGiaTTT.setText(jtblListTacGia.getValueAt(a,1).toString());
    }//GEN-LAST:event_jtblListTacGiaMouseClicked

    private void jbtnXoaTacGiaTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaTacGiaTTTActionPerformed
        // TODO add your handling code here:
        tacGiaBUS.xoaTTTacGia(jtfMaTacGiaTTT.getText());
        loadTableTacGia();
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnXoaTacGiaTTTActionPerformed

    private void jbtnXoaTrangTacGiaTTT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaTrangTacGiaTTT2ActionPerformed
        // TODO add your handling code here:
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnXoaTrangTacGiaTTT2ActionPerformed

    private void jcbbTenTGTTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbTenTGTTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbTenTGTTSActionPerformed

    private void jcbbTenTLTTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbTenTLTTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbbTenTLTTSActionPerformed

    private void jbtnThemSachTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThemSachTTTActionPerformed
        // TODO add your handling code here:
        String tenTG = String.valueOf(jcbbTenTGTTS.getSelectedItem());
        String maTG = tacGiaBUS.layMaOrTenTacGia(tenTG, true);

        String tenTL = String.valueOf(jcbbTenTLTTS.getSelectedItem());
        String maTL = theLoaiBUS.layMaOrTenTheLoai(tenTL, true);
        boolean a = sachBUS.themSachMoi(
            jtfMaSachTTT.getText(),
            maTG,
            jtfTenSachTTT.getText(),
            jtfNXBTTT.getText(),
            jtfSoLuongTTT.getText(),
            jtfGiaTienTTT.getText()
        );
        boolean b = theLoaiSachBUS.themTheLoaiSach(maTL,jtfMaSachTTT.getText());
        if(b == true && a == true){
            new MyDialog("Thêm sách thành công !!!",MyDialog.INFO_DIALOG);
        }else{
            new MyDialog("Thêm sách thất bại !!!",MyDialog.INFO_DIALOG);
        }
        loadTableTimKiem(sachBUS.getDuLieuSach());
    }//GEN-LAST:event_jbtnThemSachTTTActionPerformed

    private void jbtnXoaTrangSachTTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnXoaTrangSachTTTActionPerformed
        // TODO add your handling code here:
        resetDuLieuDaNhap();
    }//GEN-LAST:event_jbtnXoaTrangSachTTTActionPerformed

    private void jcbbTacGiaSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbTacGiaSachTKActionPerformed
        // TODO add your handling code here:
        if(jcbbNXBSachTK.getSelectedItem() == null){
            String a = (String) jcbbTacGiaSachTK.getSelectedItem();
            ArrayList<Sach> b = sachBUS.docDuLieuTimKiemSach(a,null,true,false);
            loadTableTimKiem(b);
            return;
        }
        if(jcbbNXBSachTK.getSelectedItem() != null && jcbbTacGiaSachTK.getSelectedItem() != null ){
            String a = (String) jcbbTacGiaSachTK.getSelectedItem();
            String b = (String) jcbbNXBSachTK.getSelectedItem();
            ArrayList<Sach> c = sachBUS.docDuLieuTimKiemSach(a,b,true,true);
            loadTableTimKiem(c);
            return;
        }
    }//GEN-LAST:event_jcbbTacGiaSachTKActionPerformed

    private void jcbbNXBSachTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbbNXBSachTKActionPerformed
        // TODO add your handling code here:
        if(jcbbTacGiaSachTK.getSelectedItem() == null){
            String a = (String) jcbbNXBSachTK.getSelectedItem();
            ArrayList<Sach> b = sachBUS.docDuLieuTimKiemSach(null,a,false,true);
            loadTableTimKiem(b);
            return;
        }
        if(jcbbNXBSachTK.getSelectedItem() != null && jcbbTacGiaSachTK.getSelectedItem() != null ){
            String a = (String) jcbbTacGiaSachTK.getSelectedItem();
            String b = (String) jcbbNXBSachTK.getSelectedItem();
            ArrayList<Sach> c = sachBUS.docDuLieuTimKiemSach(a,b,true,true);
            loadTableTimKiem(c);
            return;
        }
    }//GEN-LAST:event_jcbbNXBSachTKActionPerformed

    private void jbtnLuuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLuuEditActionPerformed
        // TODO add your handling code here:
        // lấy ra mã tác giả từ tên tác giả ở combobox : dùng bảng Tac Giả
        String tenTG = String.valueOf(jcbbTenTGDialog.getSelectedItem());
        String maTG = tacGiaBUS.layMaOrTenTacGia(tenTG, true);
        //lấy ra mã thể loại 
        String tenTL = String.valueOf(jcbbTheLoaiDialog.getSelectedItem());
        String maTL = theLoaiBUS.layMaOrTenTheLoai(tenTL, true);
        
        //
        
        if(jcbbTenTGDialog.getSelectedItem()==null){
            new MyDialog(" Vui lòng xác nhận tác giả !!!",MyDialog.WARNING_DIALOG);
            return ;
        }

        if(jtfTenSachDialog.getText()==""){
            new MyDialog(" Vui lòng không để trống tên sách !!!",MyDialog.WARNING_DIALOG);
            return ;
        }
        if( jtfNhaXuatBanDialog.getText()==""){
            new MyDialog(" Vui lòng không để trống tên nhà xuất bản !!!",MyDialog.WARNING_DIALOG);
            return ;
        }      
        if(jtfSoLuongDialog.getText()==""){
            new MyDialog(" Vui lòng không để trống số lượng !!!",MyDialog.WARNING_DIALOG);
            return ;
        }
        if(jtfGiaTienDialog.getText()==""){
            new MyDialog(" Vui lòng không để trống số tiền !!!",MyDialog.WARNING_DIALOG);
            return ;
        }
        
        if(jcbbTheLoaiDialog.getSelectedItem()=="null"){
            new MyDialog(" Vui lòng không để trống tên thể loại !!!",MyDialog.WARNING_DIALOG);
            return ;
        }
        MyDialog dlg = new MyDialog("Bạn có chắc chắn muốn sửa thông tin sách mã "+jtfMaSachDialog.getText()+" ?", MyDialog.WARNING_DIALOG);
        if(dlg.OK_OPTION == dlg.getAction()){
            if(theLoaiSachBUS.kiemTraTonTai(maTL, jtfMaSachDialog.getText()) == false){
                theLoaiSachBUS.suaTheLoaiSach(maTL, jtfMaSachDialog.getText());
            }

            //khi này ko còn liên kết tới bảng thể loại, sửa dù trùng mã th vẫn sửa dc
            boolean a = sachBUS.suaSach(
                   jtfMaSachDialog.getText(),
                   maTG, 
                   jtfTenSachDialog.getText(), 
                   jtfNhaXuatBanDialog.getText(), 
                   jtfSoLuongDialog.getText(), 
                   jtfGiaTienDialog.getText());

            if(a){
                new MyDialog("Sửa thành công !!!",MyDialog.INFO_DIALOG);
                dialogChinhSuaSach.dispose();
            }else{
                new MyDialog("Sửa thất bại !!!",MyDialog.INFO_DIALOG);
            }
        }
    }//GEN-LAST:event_jbtnLuuEditActionPerformed

    private void jbtnThoatEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoatEditActionPerformed
        // TODO add your handling code here:
        jtfTenSachDialog.setText("");
        jtfGiaTienDialog.setText("");
        jtfNhaXuatBanDialog.setText("");
        jtfSoLuongDialog.setText("");
        jcbbTenTGDialog.setSelectedIndex(0);
        jcbbTheLoaiDialog.setSelectedIndex(0);
        dialogChinhSuaSach.dispose();
    }//GEN-LAST:event_jbtnThoatEditActionPerformed

    private void jbtnResetEditSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetEditSActionPerformed
        // TODO add your handling code here:
        jtfTenSachDialog.setText("");
        jtfGiaTienDialog.setText("");
        jtfNhaXuatBanDialog.setText("");
        jtfSoLuongDialog.setText("");
        jcbbTenTGDialog.setSelectedIndex(0);
        jcbbTheLoaiDialog.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnResetEditSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoaSachTK;
    private javax.swing.JButton btnXuatFileSach;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dialogChinhSuaSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnChinhSuaSachTK;
    private javax.swing.JButton jbtnLuuEdit;
    private javax.swing.JButton jbtnResetEditS;
    private javax.swing.JButton jbtnSuaTacGiaTTT;
    private javax.swing.JButton jbtnSuaTheLoaiTTT;
    private javax.swing.JButton jbtnThemSachTTT;
    private javax.swing.JButton jbtnThemTacGiaTTT;
    private javax.swing.JButton jbtnThemTheLoaiTTT;
    private javax.swing.JButton jbtnThoatEdit;
    private javax.swing.JButton jbtnTimKiemSachTK;
    private javax.swing.JButton jbtnXemAllSachTK;
    private javax.swing.JButton jbtnXoaTacGiaTTT;
    private javax.swing.JButton jbtnXoaTheLoaiTTT;
    private javax.swing.JButton jbtnXoaTrangSachTTT;
    private javax.swing.JButton jbtnXoaTrangTacGiaTTT2;
    private javax.swing.JButton jbtnXoaTrangTheLoaiTTT;
    private javax.swing.JComboBox<String> jcbbListMaxMinSachTk;
    private javax.swing.JComboBox<String> jcbbNXBSachTK;
    private javax.swing.JComboBox<String> jcbbTacGiaSachTK;
    private javax.swing.JComboBox<String> jcbbTenTGDialog;
    private javax.swing.JComboBox<String> jcbbTenTGTTS;
    private javax.swing.JComboBox<String> jcbbTenTLTTS;
    private javax.swing.JComboBox<String> jcbbTheLoaiDialog;
    private javax.swing.JLabel jlblMaTaiLieuSachTK;
    private javax.swing.JLabel jlblTacGiaSachTK;
    private javax.swing.JLabel jlblTheLoaiSachTK;
    private javax.swing.JLabel jlblTitle;
    private javax.swing.JLabel jlblTongSoSachSachTK;
    private javax.swing.JLabel jlblTongSoSachTTT;
    private javax.swing.JPanel jplTimKiemSach;
    private javax.swing.JRadioButton jrdbCoBanSachTK;
    private javax.swing.JRadioButton jrdbNangCaoSachTK;
    private javax.swing.JTable jtblListSach;
    private javax.swing.JTable jtblListTacGia;
    private javax.swing.JTable jtblListTheLoai;
    private javax.swing.JTextField jtfGiaTienDialog;
    private javax.swing.JTextField jtfGiaTienTTT;
    private javax.swing.JTextField jtfMaSachDialog;
    private javax.swing.JTextField jtfMaSachTTT;
    private javax.swing.JTextField jtfMaTacGiaTTT;
    private javax.swing.JTextField jtfMaTaiLieuSachTK;
    private javax.swing.JTextField jtfMaTheLoaiTTT;
    private javax.swing.JTextField jtfNXBTTT;
    private javax.swing.JTextField jtfNhaXuatBanDialog;
    private javax.swing.JTextField jtfSoLuongDialog;
    private javax.swing.JTextField jtfSoLuongTTT;
    private javax.swing.JTextField jtfTenSachDialog;
    private javax.swing.JTextField jtfTenSachTTT;
    private javax.swing.JTextField jtfTenTacGiaTTT;
    private javax.swing.JTextField jtfTenTheLoaiTTT;
    private javax.swing.JPanel jtpSach_ThemTT;
    private javax.swing.JPanel pnlSach_TimTaiLieu;
    // End of variables declaration//GEN-END:variables
    private void showAndLoadComboboxStart(){
        
        //show comboBox tac gia o timkiem tai lieu và thêm tài liệu
        jcbbTenTGTTS.removeAllItems();
        jcbbTacGiaSachTK.removeAllItems();
        jcbbTenTGDialog.removeAllItems();
        ArrayList<String> cbTG = tacGiaBUS.getListTenTacGia();
        for(String tg : cbTG){
            jcbbTacGiaSachTK.addItem(tg);
            jcbbTenTGTTS.addItem(tg);
            jcbbTenTGDialog.addItem(tg);
        }
        
        
        //show comboBox nhà xuất bản o timkiem tai lieu
        jcbbNXBSachTK.removeAllItems();
        ArrayList<String> cbNXB = sachBUS.getListNXB();
        jcbbNXBSachTK.addItem("");
        for(String tl : cbNXB){
            jcbbNXBSachTK.addItem(tl);
        }
        
        //show comboBox the loai o thêm tai lieu
        jcbbTenTLTTS.removeAllItems();
        jcbbTheLoaiDialog.removeAllItems();
        ArrayList<String> cbTL = theLoaiBUS.getListTenTheLoai();
        for(String tl : cbTL){
            jcbbTenTLTTS.addItem(tl);
            jcbbTheLoaiDialog.addItem(tl);
        }
        
    }
      
    private void showStartSach(){
        //show các radio đi kèm button,label
        jlblTacGiaSachTK.setVisible(false);
        jlblTheLoaiSachTK.setVisible(false);
        jcbbTacGiaSachTK.setVisible(false);
        jcbbNXBSachTK.setVisible(false);
        jrdbCoBanSachTK.setSelected(true);
        jcbbListMaxMinSachTk.setVisible(true);
        //show comboBox max, min xem theo yêu cầu ở phần tìm kiếm sách
        ArrayList<String> cbMaxMin = new ArrayList<>();
        cbMaxMin.add("ASC của số lượng");
        cbMaxMin.add("DESC của số lượng");
        cbMaxMin.add("ASC của giá tiền");
        cbMaxMin.add("DESC của giá tiền");
        cbMaxMin.add("ASC của tên sách");
        for(String mn : cbMaxMin){
            jcbbListMaxMinSachTk.addItem(mn);
        }
        //
        loadTableColumn();
        chinhColumn(jtblListTheLoai);
        chinhColumn(jtblListTacGia);
        //show các bảng trong thẻ card SÁCH
        loadTableTimKiem(sachBUS.getDuLieuSach());       
        loadTableTheLoai();       
        loadTableTacGia();
        
        //show combobox tac giả thể lại bên thông tin sách
        showAndLoadComboboxStart();
    }
    
    private void loadTableTheLoai(){
        //setRowCount: đưa cái table số dòng về 0 tránh tình trạng lặp dữ liệu khi đưa vào bảng
        tabModelTheLoai.setRowCount(0);
        ArrayList<TheLoai> theLoaiList = theLoaiBUS.getListTheLoai();
        for(TheLoai tl : theLoaiList){
            tabModelTheLoai.addRow(new Object[]{tl.getMaTheLoai(),tl.getTenTheLoai()});
        }
        jtblListTheLoai.clearSelection();
        showAndLoadComboboxStart();
    }
    
    private void loadTableTacGia(){
        //setRowCount: đưa cái table số dòng về 0 tránh tình trạng lặp dữ liệu khi đưa vào bảng
        tabModelTacGia.setRowCount(0);
        ArrayList<TacGia> tacGiaList = tacGiaBUS.getListTacGia();
        for(TacGia tg : tacGiaList){
            tabModelTacGia.addRow(new Object[]{tg.getMaTacGia(),tg.getTenTacGia()});
        }       
        jtblListTacGia.clearSelection();          
        showAndLoadComboboxStart();
    }
    
    private void loadTableTimKiem(ArrayList<Sach> a){
        tabModelSach.setRowCount(0);
        sachList = a;
        for(Sach sach : sachList){
            tabModelSach.addRow(new Object[]{tabModelSach.getRowCount()+1,sach.getMaSach(),sach.getMaTacGia(),sach.getTenSach(),sach.getNxb(),sach.getSoLuong(),sach.getGiaTien()});
        }
        jlblTongSoSachTTT.setText(String.valueOf(tabModelSach.getRowCount()));
        jlblTongSoSachSachTK.setText("Số đầu sách : "+String.valueOf(tabModelSach.getRowCount()));
    }
    
    private void loadTableColumn(){
        ArrayList<String> tab = new ArrayList<>();
        tab.add(0, "STT");
        tab.add(1, "Mã sách");
        tab.add(2, "Tên tác giả");
        tab.add(3, "Tên sách");
        tab.add(4, "Nhà xuất bản");
        tab.add(5, "Số lượng");
        tab.add(6, "Giá tiền");
//        tab.add(7, "Tên thể loại");        
        for(String a : tab){
            tabModelSach.addColumn(a);
        }
        chinhColumn(jtblListSach);
    }
    
    private void resetDuLieuDaNhap(){
        jtfMaTacGiaTTT.setText("");
        jtfTenTacGiaTTT.setText("");
        jtfMaTheLoaiTTT.setText("");
        jtfTenTheLoaiTTT.setText("");
        jtfMaSachTTT.setText((""));
        jtfTenSachTTT.setText((""));
        jtfSoLuongTTT.setText((""));
        jtfNXBTTT.setText((""));
        jtfGiaTienTTT.setText((""));
    }
    
    private void chinhColumn(JTable tbl){
        JTableHeader header = tbl.getTableHeader();
        
        Font font = new Font("Arial", Font.BOLD, 40);
        header.setBackground(new Color(242, 153, 74));
        header.setFont(new Font("Arial", Font.BOLD, 24));
        header.setOpaque(false);
        header.setForeground(Color.BLACK);
        header.setReorderingAllowed(false);
        
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
    }
}
