/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLTV.GUI;

import MyCustom.XuLyFileExcel;
import QLTV.BUS.ThongKeBUS;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
/**
 *
 * @author chihi
 */
public class pnThongKeGUI extends javax.swing.JPanel {
    DefaultTableModel tableModelThongKe;
    ThongKeBUS thongKeBUS;
    /**
     * Creates new form pnThongKeGUI
     */
    public pnThongKeGUI() {
        initComponents();
        thongKeBUS = new ThongKeBUS();
        tableModelThongKe = (DefaultTableModel) tblBangThongKe.getModel();
        loadTable(1);
        lblSoDauSach.setText(String.valueOf(thongKeBUS.getTongSoDauSach()));
        lblTongSoSach.setText(String.valueOf(thongKeBUS.getTongSachKho()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThongKe = new javax.swing.JButton();
        btnXuatExcel = new javax.swing.JButton();
        jycNam = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSoDauSach = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTongSoSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangThongKe = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 410, 145, 43));

        btnXuatExcel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnXuatExcel.setText("Xuất excel");
        btnXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatExcelActionPerformed(evt);
            }
        });
        add(btnXuatExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 410, 142, 43));

        jycNam.setName("jycNam"); // NOI18N
        add(jycNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 90, 43));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Số đầu sách trong kho");

        lblSoDauSach.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(lblSoDauSach, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSoDauSach, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tổng số sách trong kho");

        lblTongSoSach.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTongSoSach, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongSoSach, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 40, -1, -1));

        tblBangThongKe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblBangThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Quý 1", "Quý 2", "Quý 3", "Qúy 4"
            }
        ));
        tblBangThongKe.setRowHeight(40);
        jScrollPane1.setViewportView(tblBangThongKe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 1087, 160));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        loadTable(jycNam.getYear());
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatExcelActionPerformed
        // TODO add your handling code here:
        XuLyFileExcel xuatFile = new XuLyFileExcel();
        xuatFile.xuatExcel(tblBangThongKe);
    }//GEN-LAST:event_btnXuatExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnXuatExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jycNam;
    private javax.swing.JLabel lblSoDauSach;
    private javax.swing.JLabel lblTongSoSach;
    private javax.swing.JTable tblBangThongKe;
    // End of variables declaration//GEN-END:variables
    private void loadTable(int nam) {
        chinhColumn();
        tableModelThongKe.setRowCount(0);
        tableModelThongKe.addRow(new Object[]{
            "Số sách mượn",
            thongKeBUS.getSoSachMuon(nam, 1),
            thongKeBUS.getSoSachMuon(nam,2),
                thongKeBUS.getSoSachMuon(nam,3),
                thongKeBUS.getSoSachMuon(nam, 4)
            });
        tableModelThongKe.addRow(new Object[]{
            "Số sách hư hao",
            thongKeBUS.getSoSachHong(nam, 1),
            thongKeBUS.getSoSachHong(nam,2),
                thongKeBUS.getSoSachHong(nam,3),
                thongKeBUS.getSoSachHong(nam, 4)
            });
        
    }
    
    private void chinhColumn(){
        JTableHeader header = tblBangThongKe.getTableHeader();
        
        Font font = new Font("Arial", Font.BOLD, 40);
        header.setBackground(new Color(242, 153, 74));
        header.setFont(new Font("Arial", Font.BOLD, 24));
        header.setOpaque(false);
        header.setForeground(Color.BLACK);
        header.setReorderingAllowed(false);
        
        ((DefaultTableCellRenderer) header.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
    }
}
